### ISSUE TITLE
How to add a provenance file to a docker image

### ISSUE THREAD

**Issue by Brend-Smits** [philips-labs/slsa-provenance-action#12]
- [x] #13
- [x] #14

**Comment by developer-guy** [comment]
Hello, @Brend-Smits, the [cosign](https://github.com/sigstore/cosign) has the support of uploading attestation files to the OCI Registry signing them.

```shell
$ cosign attest --key cosign.key --predicate <path> <image-uri>
```

Thomas Meadows asked that question in [cosign's Slack channel](https://sigstore.slack.com/archives/C01PZKDL4DP/p1639446407048400).

> Hey all! I am currently in the process of configuring https://github.com/philips-labs/slsa-provenance-action in a GitHub action to generate an attestation. I want to then take that created json and push it as an OCI manifest (.att)  to the image repository against the image using cosign. How would I go about doing this?

I want to take care of this one, but I have a couple of questions first:

* Do we want to sign the provenance files while uploading them to the OCI Registry?
* Which method do you prefer for using cosign, as an executable or a Go module?

**Comment by ChaosInTheCRD** [comment]
Thanks for the input here @developer-guy! I think signing the provenance files while uploading them would be very helpful? Unless anyone can think of a reason why we would want to avoid it.

**Comment by developer-guy** [comment]
yes, it'd be helpful no doubt. Also, we can do it with a keyless approach which leads us to the second item in the list, do we want to use cosign as an executable over `os.Exec` package, or a Go module?

**Comment by developer-guy** [comment]
I've started another issue on cosign
* https://github.com/sigstore/cosign/issues/1202

**Comment by ChaosInTheCRD** [comment]
My only reservation with keyless is that it doesn't provide an option for private repositories. I guess though that this is in the minority of cases.

**Comment by marcofranssen** [comment]
Resolved by #88

**Comment by marcofranssen** [comment]
Correction we might still want to integrate this in the binary so no additional step is required.

**Comment by marcofranssen** [comment]
Created a new dedicated issue to work on having a more native integration for docker images #129
