### ISSUE TITLE
Action is not able to pull private images

### ISSUE THREAD

**Issue by Brend-Smits** [philips-labs/slsa-provenance-action#125]
The action is not able to pull private images at this point. This is due to the library that is used internally to retrieve the images is not passing along the proper tokens.

**Comment by marcofranssen** [comment]
See https://github.com/sigstore/cosign/blob/757252063bf4724f11a52336ef13a724059a39b6/pkg/oci/remote/options.go#L51
and 
https://github.com/google/go-containerregistry/blob/main/pkg/authn/keychain.go#L65

on how to resolve and authenticate the docker client.
