### ISSUE TITLE
Use att extension for provenance

### ISSUE THREAD

**Issue by marcofranssen** [philips-labs/slsa-provenance-action#128]
Align the provenance extension with the extension used by cosign.

https://github.com/sigstore/cosign/blob/bad18e5cb25f2cb86301d248e7e4ed39d49df143/pkg/cosign/fetch.go#L63

**Comment by Brend-Smits** [comment]
We are already using .att right? See: https://github.com/philips-labs/slsa-provenance-action/pkgs/container/slsa-provenance/versions
Can you elaborate or close this issue @marcofranssen ?

**Comment by marcofranssen** [comment]
We are not in our release assets and when creating the provenance. There it is still by default on `provenance.json`.

For containers you are right. This issue is about aligning that with the containers.

**Comment by Brend-Smits** [comment]
Gotcha @marcofranssen, I will align this in my PR #134
