### ISSUE TITLE
Docker: Create a provenance file - attach it via de build pipeline

### ISSUE THREAD

**Issue by Brend-Smits** [philips-labs/slsa-provenance-action#13]
Manually create a provenance file for curl, based on this example: https://slsa.dev/example

**Comment by JeroenKnoops** [comment]
Manual provenance file: https://github.com/philips-labs/SLSA-Provenance-Usecases/commit/5d4d7f42e6e7f3631b9edc6fddeffcfb887b1474

**Comment by marcofranssen** [comment]
Resolved by #88
