### ISSUE TITLE
use keyless approach to sign and verify project

### ISSUE THREAD

**Issue by developer-guy** [philips-labs/slsa-provenance-action#137]
slsa-provenance project seems to be using public/private key pairs to sign and verify its binaries/container images. We can change it to keyless approach, please feel free to assign it to me if you accep the idea.

**Comment by Brend-Smits** [comment]
Hey @developer-guy,
Thank you for creating this issue. Can you explain a little bit more about what your plans would be?

**Comment by developer-guy** [comment]
slsa-provenance CLI tool using keyful approach which means that it uses [public/private key pairs](https://github.com/philips-labs/slsa-provenance-action/blob/4ebaa6ca374931c6cd9b9e81336f834395cc47a2/.github/workflows/ci.yaml#L110) to sign and verify its [binary](https://github.com/philips-labs/slsa-provenance-action/blob/4ebaa6ca374931c6cd9b9e81336f834395cc47a2/.goreleaser.yml?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L68) & [container images](https://github.com/philips-labs/slsa-provenance-action/blob/4ebaa6ca374931c6cd9b9e81336f834395cc47a2/.goreleaser.yml?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L106), we remove these keys if we can use the keyless approach of cosign that uses Rekor Transparency Log server.

**Comment by marcofranssen** [comment]
@developer-guy would be great if we can offer both options, by reusing the cosign libs in our cli

**Comment by developer-guy** [comment]
@marcofranssen this is related to signing slsa-provenance binary with keyless approach actually, but yeah, that might be another issue as well using cosign libs 🙋🏻‍♂️

**Comment by marcofranssen** [comment]
Duplicate #122

**Comment by developer-guy** [comment]
I think you got me wrong 🙈 what I want to say is that we can use a keyless (by removing public/private key pairs) approach to sign slsa-provenance binary, this issue is related to that actually 🙋🏻‍♂️

**Comment by developer-guy** [comment]
can you please re-open the issue @marcofranssen 🙏

**Comment by marcofranssen** [comment]
@developer-guy in #122 we would like to switch to use the keyless approach. For now we choose not to use it as it is still an experimental feature of cosign. By Switching to this keyless approach we will also get a few other benefits like the rekor transparancey log as well pkcs11 certificates.
