### ISSUE TITLE
Rename SBOM artifacts to exclude ".tar.gz"

### ISSUE THREAD

**Issue by Brend-Smits** [philips-labs/slsa-provenance-action#157]
See: https://github.com/philips-labs/slsa-provenance-action/releases/tag/v0.7.2
SBOMs are included, but they use the full artifact name including the .tar.gz, can we remove the .tar.gz part? Unsure if this is possible within GoReleaser

**Comment by marcofranssen** [comment]
I think it is fine to keep the `tar.gz` part as it nicely inidicates this is the SBOM for that downloadable asset from the GitHub release.

Go releaser could e.g. also be configured to only release the binaries (without the compressions). In that case you would have both the tar.gz and the binary as an asset.
