### ISSUE TITLE
CODEOWNERS is not assigning the secure-software-supply-chain as a reviewer.

### ISSUE THREAD

**Issue by marcofranssen** [philips-labs/SLSA-Provenance-Action#21]
The @philips-labs/secure-software-supply-chain team isn't assigned to PRs automatically, despite the fact this team is configured as code owner.

**Comment by Brend-Smits** [comment]
I think this might need to be configured in the repo settings. I will check.

**Comment by Brend-Smits** [comment]
Should be fixed now. I also enabled the requirement of signing commits on all branches.
