### ISSUE TITLE
Dependabot build fails

### ISSUE THREAD

**Issue by JeroenKnoops** [philips-labs/slsa-provenance-action#58]
## Problem

Dependabot build fails on generating the provenance file.

### Error message
```
2021/10/18 08:01:01 failed to unmarshal github context json: invalid character 'h' in string escape code
```
### Error job
https://github.com/philips-labs/slsa-provenance-action/pull/55/checks?check_run_id=3923877684

**Comment by JeroenKnoops** [comment]
Workflow is failing on pull-request build.

GitHub events are not the same for the same commit.

## Examples.

Two events from the same commit:
- [push example event](https://github.com/JeroenKnoops/test-github-pull-request-event/runs/3939970450?check_suite_focus=true)
- [pull request example event](https://github.com/JeroenKnoops/test-github-pull-request-event/runs/3939971544?check_suite_focus=true)

**Comment by ribbybibby** [comment]
I think I'm running into the same issue described here where the content of the commit message can mess up the escaping and cause the action to fail:
https://github.com/ribbybibby/testy/runs/4596564618?check_suite_focus=true#step:5:63

The commit message in this case is:
```
Make @a change
"@in quotes"
```

Do you need to pass the whole github and runner contexts as json? Could you pass the individual fields you need in instead as flags?

**Comment by ribbybibby** [comment]
Or, get everything from the environment variables instead: https://docs.github.com/en/actions/learn-github-actions/environment-variables#default-environment-variables?

**Comment by marcofranssen** [comment]
This issue has been resolved.
