### ISSUE TITLE
Investigate Builder ID

### ISSUE THREAD

**Issue by Brend-Smits** [philips-labs/slsa-provenance-action#6]
What does it do?
Example: 
```
  "predicate": {
    "builder": {
      "id": "https://github.com/philips-labs/SLSA-Provenance-Action/Attestations/GitHubHostedActions@v1"
    },
```

What does the URL do and what precisely does the Attesations mean?

**Comment by JeroenKnoops** [comment]
From documentation on https://slsa.dev/provenance/v0.1 :

```
builder.id string (TypeURI), required

URI indicating the builder’s identity.
```

**Comment by Brend-Smits** [comment]
We think that the Builder ID is subject to change and will be used to verify the builder's identity. The builder in our case is Github-hosted runners. Github will provide some kind of endpoint or URL to verify the identity of the builder. Since this is not yet implemented by Github, this can be set as a low priority for now.
